DROP TABLE IF EXISTS demo.CAVE CASCADE;
CREATE TABLE demo.CAVE (
	CAVE_ID SERIAL PRIMARY KEY,
	CAVE_NAME VARCHAR NOT NULL,
	MAX_BEARS INTEGER DEFAULT 2
);

DROP TABLE IF EXISTS demo.BEAR_TYPE CASCADE;
CREATE TABLE demo.BEAR_TYPE (
	BEAR_TYPE_ID SERIAL PRIMARY KEY,
	BEAR_TYPE_NAME VARCHAR NOT NULL,
	SURVIVAL VARCHAR DEFAULT 'Not Extinct'
);


DROP TABLE IF EXISTS demo.BEAR CASCADE;
CREATE TABLE demo.BEAR (
	BEAR_ID SERIAL PRIMARY KEY,
	BEAR_NAME VARCHAR NOT NULL,
	BEAR_WEIGHT INTEGER NOT NULL DEFAULT 0,
	CAVE_ID INTEGER REFERENCES demo.CAVE (CAVE_ID),
	BEAR_TYPE_ID INTEGER REFERENCES demo.BEAR_TYPE (BEAR_TYPE_ID),
	BEAR_BIRTHDATE TIMESTAMP DEFAULT now()
);

DROP TABLE IF EXISTS demo.BEEHIVE CASCADE;
CREATE TABLE demo.BEEHIVE (
	BEEHIVE_ID SERIAL PRIMARY KEY,
	BEEHIVE_NAME VARCHAR NOT NULL,
	WEIGHT NUMERIC(5, 2) NOT NULL DEFAULT 55
);

INSERT INTO demo.BEAR_TYPE (BEAR_TYPE_NAME, SURVIVAL) VALUES
	('Polar', 'Not Extinct'),
	('Brown', 'Not Extinct'),
	('American Black', 'Not Extinct'),
	('Panda', 'Not Extinct'),
	('Cave', 'Extinct'),
	('Pooh', 'Magical'),
	('Sloth', 'Extinct');

INSERT INTO demo.CAVE (CAVE_NAME, MAX_BEARS) VALUES
	('Yaskeenya Niecwiedza', 200),
	('Carlsbad Caverns', 15),
	('Ash Hollow Cave', 4);
	
INSERT INTO demo.BEAR (BEAR_NAME, BEAR_WEIGHT, CAVE_ID, BEAR_TYPE_ID) VALUES
	('Winnie', 200, 1, 6),
	('Baloo', 310, 2, 7);

INSERT INTO demo.BEEHIVE (BEEHIVE_NAME, WEIGHT) VALUES
	('My Personal Beehive', 25.35);