apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-service-deployment
  labels:
    app: kubernetes-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-service
  template:
    metadata:
      labels:
        app: kubernetes-service
    spec:
      containers:
      - name: kubernetes
        image: ikenoxamos/kubernetes-service:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
